server:
  port: 9080
dubbo:
  application:
    name: dubbo-spring-boot-nacos-provider
    qos-enable: true
    qos-port: 22222
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848?username=nacos&password=nacos